
using System;

namespace Scalesque {

	//Warning: This file was generated by a T4 template.  Any manual changes you make maybe overwritten when the templating code activates.

	/// <summary>
    /// An implementation of partially applied functions
    /// </summary>
	public static class PartialFunctions {

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 1
		/// </summary>
		public static Func<TResult> Partial<T1,TResult>(this Func<T1,TResult> f, T1 value1) {
			return ()=>f(value1);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 2
		/// </summary>
		public static Func<T2,TResult> Partial<T1,T2,TResult>(this Func<T1,T2,TResult> f, T1 value1) {
			return (value2)=>f(value1,value2);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 2
		/// </summary>
		public static Func<TResult> Partial<T1,T2,TResult>(this Func<T1,T2,TResult> f, T1 value1, T2 value2) {
			return ()=>f(value1,value2);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 3
		/// </summary>
		public static Func<T2,T3,TResult> Partial<T1,T2,T3,TResult>(this Func<T1,T2,T3,TResult> f, T1 value1) {
			return (value2,value3)=>f(value1,value2,value3);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 3
		/// </summary>
		public static Func<T3,TResult> Partial<T1,T2,T3,TResult>(this Func<T1,T2,T3,TResult> f, T1 value1, T2 value2) {
			return (value3)=>f(value1,value2,value3);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 3
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,TResult>(this Func<T1,T2,T3,TResult> f, T1 value1, T2 value2, T3 value3) {
			return ()=>f(value1,value2,value3);
		}

		/// <summary>
		/// Creates a partially applied function of arity 3 from a function of arity 4
		/// </summary>
		public static Func<T2,T3,T4,TResult> Partial<T1,T2,T3,T4,TResult>(this Func<T1,T2,T3,T4,TResult> f, T1 value1) {
			return (value2,value3,value4)=>f(value1,value2,value3,value4);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 4
		/// </summary>
		public static Func<T3,T4,TResult> Partial<T1,T2,T3,T4,TResult>(this Func<T1,T2,T3,T4,TResult> f, T1 value1, T2 value2) {
			return (value3,value4)=>f(value1,value2,value3,value4);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 4
		/// </summary>
		public static Func<T4,TResult> Partial<T1,T2,T3,T4,TResult>(this Func<T1,T2,T3,T4,TResult> f, T1 value1, T2 value2, T3 value3) {
			return (value4)=>f(value1,value2,value3,value4);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 4
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,T4,TResult>(this Func<T1,T2,T3,T4,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4) {
			return ()=>f(value1,value2,value3,value4);
		}

		/// <summary>
		/// Creates a partially applied function of arity 4 from a function of arity 5
		/// </summary>
		public static Func<T2,T3,T4,T5,TResult> Partial<T1,T2,T3,T4,T5,TResult>(this Func<T1,T2,T3,T4,T5,TResult> f, T1 value1) {
			return (value2,value3,value4,value5)=>f(value1,value2,value3,value4,value5);
		}

		/// <summary>
		/// Creates a partially applied function of arity 3 from a function of arity 5
		/// </summary>
		public static Func<T3,T4,T5,TResult> Partial<T1,T2,T3,T4,T5,TResult>(this Func<T1,T2,T3,T4,T5,TResult> f, T1 value1, T2 value2) {
			return (value3,value4,value5)=>f(value1,value2,value3,value4,value5);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 5
		/// </summary>
		public static Func<T4,T5,TResult> Partial<T1,T2,T3,T4,T5,TResult>(this Func<T1,T2,T3,T4,T5,TResult> f, T1 value1, T2 value2, T3 value3) {
			return (value4,value5)=>f(value1,value2,value3,value4,value5);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 5
		/// </summary>
		public static Func<T5,TResult> Partial<T1,T2,T3,T4,T5,TResult>(this Func<T1,T2,T3,T4,T5,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4) {
			return (value5)=>f(value1,value2,value3,value4,value5);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 5
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,T4,T5,TResult>(this Func<T1,T2,T3,T4,T5,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5) {
			return ()=>f(value1,value2,value3,value4,value5);
		}

		/// <summary>
		/// Creates a partially applied function of arity 5 from a function of arity 6
		/// </summary>
		public static Func<T2,T3,T4,T5,T6,TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1) {
			return (value2,value3,value4,value5,value6)=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 4 from a function of arity 6
		/// </summary>
		public static Func<T3,T4,T5,T6,TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1, T2 value2) {
			return (value3,value4,value5,value6)=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 3 from a function of arity 6
		/// </summary>
		public static Func<T4,T5,T6,TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1, T2 value2, T3 value3) {
			return (value4,value5,value6)=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 6
		/// </summary>
		public static Func<T5,T6,TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4) {
			return (value5,value6)=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 6
		/// </summary>
		public static Func<T6,TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5) {
			return (value6)=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 6
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,T4,T5,T6,TResult>(this Func<T1,T2,T3,T4,T5,T6,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6) {
			return ()=>f(value1,value2,value3,value4,value5,value6);
		}

		/// <summary>
		/// Creates a partially applied function of arity 6 from a function of arity 7
		/// </summary>
		public static Func<T2,T3,T4,T5,T6,T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1) {
			return (value2,value3,value4,value5,value6,value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 5 from a function of arity 7
		/// </summary>
		public static Func<T3,T4,T5,T6,T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2) {
			return (value3,value4,value5,value6,value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 4 from a function of arity 7
		/// </summary>
		public static Func<T4,T5,T6,T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2, T3 value3) {
			return (value4,value5,value6,value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 3 from a function of arity 7
		/// </summary>
		public static Func<T5,T6,T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4) {
			return (value5,value6,value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 7
		/// </summary>
		public static Func<T6,T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5) {
			return (value6,value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 7
		/// </summary>
		public static Func<T7,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6) {
			return (value7)=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 7
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,T4,T5,T6,T7,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6, T7 value7) {
			return ()=>f(value1,value2,value3,value4,value5,value6,value7);
		}

		/// <summary>
		/// Creates a partially applied function of arity 7 from a function of arity 8
		/// </summary>
		public static Func<T2,T3,T4,T5,T6,T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1) {
			return (value2,value3,value4,value5,value6,value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 6 from a function of arity 8
		/// </summary>
		public static Func<T3,T4,T5,T6,T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2) {
			return (value3,value4,value5,value6,value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 5 from a function of arity 8
		/// </summary>
		public static Func<T4,T5,T6,T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3) {
			return (value4,value5,value6,value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 4 from a function of arity 8
		/// </summary>
		public static Func<T5,T6,T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4) {
			return (value5,value6,value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 3 from a function of arity 8
		/// </summary>
		public static Func<T6,T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5) {
			return (value6,value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 2 from a function of arity 8
		/// </summary>
		public static Func<T7,T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6) {
			return (value7,value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 1 from a function of arity 8
		/// </summary>
		public static Func<T8,TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6, T7 value7) {
			return (value8)=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		/// <summary>
		/// Creates a partially applied function of arity 0 from a function of arity 8
		/// </summary>
		public static Func<TResult> Partial<T1,T2,T3,T4,T5,T6,T7,T8,TResult>(this Func<T1,T2,T3,T4,T5,T6,T7,T8,TResult> f, T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6, T7 value7, T8 value8) {
			return ()=>f(value1,value2,value3,value4,value5,value6,value7,value8);
		}

		
	}
}